uint8 controller_mode
int32 target_id       # Likely target ID or -1 if hidden
float64 goal_x        # in map frame (only if controller_mode == SET_GOAL)
float64 goal_y        # in map frame (only if controller_mode == SET_GOAL)
float64 target_pos_x  # in odom frame (obtained from current belief even if target is hidden)
float64 target_pos_y  # in odom frame (obtained from current belief even if target is hidden)
float64 target_yaw    # in odom frame (obtained from current belief even if target is hidden)
float64 target_vel    
---
uint8 error_code
